import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import "leaflet/dist/leaflet.css";
import Providers from "@/components/Providers";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Zold Gold Wallet",
  description: "Generated by create next app",
  icons: {
    icon: "/02.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.variable} h-screen bg-gray-50 antialiased dark:bg-neutral-600`}
      >
        <ThemeProvider
          defaultTheme="light"
          enableSystem={false}
          attribute="class"
        >
          <Providers>{children}</Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
